# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The concmd gradle plugin
tagline:          'Write concordion tests in markdown'
baseurl: "/concmd/"


author:
  name:           'Neel Smith'
 
paginate:         5


links:
  - title: Release notes
    url: releases
  - title: Github repository
    url: https://github.com/neelsmith/concmdplugin
    external: true
  - title: Neel Smith on github
    url: http://neelsmith.github.io/
    external: true
   